apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
#  commented out due to googleCloudBuild
# local:
#    push: false
  googleCloudBuild:
    projectId: ticketing-dev-320907
  artifacts:
    - image: us.gcr.io/ticketing-dev-320907/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .